# Generated by Django 4.1.3 on 2022-11-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='user_relations_id',
            new_name='user_relations',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='userrelation',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='userrelation',
            old_name='following_id',
            new_name='following',
        ),
    ]
