export const FETCH_LESSON = 'FETCH_LESSON';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_CHOICES = 'FETCH_CHOICES';
export const CREATE_ANSWER = 'CREATE_ANSWER';
export const FETCH_ANSWERS = 'FETCH_ANSWERS';
